
services:
  postgres:
    image: postgres:latest
    container_name: calculator_db
    environment:
      POSTGRES_USER: calc_user
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: calculator_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5443:5432"

volumes:
  postgres_data: