env: "local"

db:
  host: "calculator_db"
  port: "5443"
  name: "calculator_db"
  user: "calc_user"
  password: "pwd123"
  sslmode: "disable"

http_server:
  address: "0.0.0.0:8080"  
  timeout: 4s
  idle_timeout: 60s
